### PR TITLE
Capture tests artifacts and publish to gh-pages

### LINKED ISSUE #58: Capture artifacts generated during builds on drone CI

### PR DESCRIPTION
**Pull request by niltonvasques**
* Using a recursive and theirs strategy to keep [gh-pages](https://pages.github.com/) history
* Move tests commands from drone.yml to tests.sh
* Capture logcat log and upload to gh-pages
* [Using drone secrets to pass sensible data to builds](http://readme.drone.io/usage/secrets/)

The last artifacts could be seen through these urls:

* [Instrumentation tests](https://catbag.github.io/redux-android-sample/app/build/reports/androidTests/connected/)
* [Unit tests](https://catbag.github.io/redux-android-sample/app/build/reports/tests)
* [PMD](https://catbag.github.io/redux-android-sample/app/build/reports/pmd/pmd.html)
* [Findbugs](https://catbag.github.io/redux-android-sample/app/build/reports/findbugs/findbugs.html)
* [Checkstyle](https://catbag.github.io/redux-android-sample/app/build/reports/checkstyle/checstyle.html)
* [Artifacts history](https://github.com/Catbag/redux-android-sample/tree/gh-pages)

Fixes #58

### CODE REVIEW

**Review by raulccabreu — COMMENTED** [review]
:+1: but tests have failed

**Comment by niltonvasques** [comment]
@raulccabreu Do you think that is appropriated fix ui tests in this PR?

**Comment by niltonvasques** [comment]
@raulccabreu Looks like that drone don't have started the builds for last commits.

**Comment by raulccabreu** [comment]
I'm thinking to fix test issues #51 on another PR...the problem is that my old PR that pushes a first fix attempt passes, you have put the tests to loop? Passes to me the script that loops tests please.

**Comment by niltonvasques** [comment]
@raulccabreu: 

``` bash
COUNT=1; 
while [ $? -eq 0 ]; do 
  echo "Tests number "$COUNT; 
  COUNT=$((COUNT + 1)); 
  ./gradlew cC --daemon; 
done
```

**Review by fpbitencourt — APPROVED** [review]

**Pull request merged**
