### PR TITLE
Upgrade architecture chart to reflect recent changes in project

### PR DESCRIPTION
**Pull request by niltonvasques**
* Add middlewares layer in architecture chart
* Remove server side architecture
* Add Riffsy API info
* Represent unique elements and many elements in chart

### CODE REVIEW

**Review by raulccabreu — CHANGES_REQUESTED** [review]
We don't use constraint layouts and will not use too soon in this sample...so...you can remove it from "Anvil/React/Constraint/Views"

**Comment by raulccabreu** [comment]
Good upgrade, i made a request change. :100:

**Comment by niltonvasques** [comment]
@raulccabreu updated!

**Review by raulccabreu — APPROVED** [review]

**Comment by raulccabreu** [comment]
Approved! :+1:

**Pull request merged**
