### PR TITLE
Run tests on emulator 22

### PR DESCRIPTION
**Pull request by niltonvasques**

### CODE REVIEW

**Comment by raulccabreu** [comment]
I cleaned the host, removing some unused docker images. This image in your PR has the two emulators? Or has one image only?

**Comment by raulccabreu** [comment]
Other question this is a test to solve the last build emulator problem?

**Comment by niltonvasques** [comment]
The image has only one emulator. It was a try to solve the weird errors on master.

**Comment by niltonvasques** [comment]
I will close this for now!

**Pull request closed without merging**
